controller:
  properies:
    first: d

server:
  port: 8080
#-Djavax.net.debug=all
trust-store: classpath:keystore/baeldung2.p12
trust-store-password: password
#    key-alias: baeldung
#    enabled: true
#  trust.store='C:\Users\V\baeldung.p12'
#  #trust store password
#  trust.store.password=passw0rd

management:
  endpoints:
    enabled-by-default: true
    info:
      enabled: true
    web:
      exposure:
        include: health,info,beans,conditions
      base-path: /management