controller:
  properies:
    first: 'It is first Controller properties'

server:
  port: 8086
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore/baeldung2.p12
    key-store-password: password
    key-alias: localhost
    enabled: true

logging:
  level:
    org:
      springframework: TRACE