mailExample:
  host: smtp.googlemail.com
  port: 587
  username: test.loayl@gmail.com
  password: cuhgwlsqsqgqcrxt
  poll-rate: 10000

tacocloud:
  api:
    url: http://localhost:8080/orders/fromEmail

spring:
  main:
    web-application-type: none #отключить автоконфигурацию Spring  MVC

#tacocloud:
#  email:
#    host: imap.tacocloud.com
#    mailbox: INBOX
#    username: taco-in-flow
#    password: 1L0v3T4c0s
#    poll-rate: 10000